# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-64bit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      # Runs a set of commands using the runners shell
      - name: Download latest client
        run: |
          curl -LO https://cdn.classicube.net/client/release/osx64/ClassiCube.tar.gz

      - name: Update executable
        run: |
          chmod +x ClassiCube

      - name: Make .app bundle
        run: |
          mkdir -p ./ClassiCube.app/Contents/MacOS
          mv ./ClassiCube ./ClassiCube.app/Contents/MacOS/ClassiCube
          mkdir -p ./ClassiCube.app/Contents/Resources
          cp ./icon.icns ./ClassiCube.app/Contents/Resources/icon.icns
          cp ./Info.plist ./ClassiCube.app/Contents/Info.plist
          tar -czvf ClassiCube-x64.tar.gz ./ClassiCube.app

      - name: Upload .app bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: ClassiCube-x64
          # A file, directory or wildcard pattern that describes what to upload
          path: ClassiCube-x64.tar.gz
          # The desired behavior if no files are found using the provided path.
  # This workflow contains a single job called "build"
  build-32bit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      # Runs a set of commands using the runners shell
      - name: Download latest client
        run: |
          curl -LO https://cdn.classicube.net/client/release/osx32/ClassiCube.tar.gz
          tar -xvzf ./ClassiCube.tar.gz

      - name: Update executable
        run: |
          chmod +x ClassiCube

      - name: Make .app bundle
        run: |
          mkdir -p ./ClassiCube.app/Contents/MacOS
          mv ./ClassiCube ./ClassiCube.app/Contents/MacOS/ClassiCube
          mkdir -p ./ClassiCube.app/Contents/Resources
          cp ./icon.icns ./ClassiCube.app/Contents/Resources/icon.icns
          cp ./Info.plist ./ClassiCube.app/Contents/Info.plist
          tar -czvf ClassiCube-x86.tar.gz ./ClassiCube.app

      - name: Upload .app bundle
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: ClassiCube-x86
          # A file, directory or wildcard pattern that describes what to upload
          path: ClassiCube-x86.tar.gz
          # The desired behavior if no files are found using the provided path.
  release:
    runs-on: ubuntu-latest
    needs: [build-32bit, build-64bit]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: ClassiCube-x86
          # Destination path
          path: ClassiCube-x86

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: ClassiCube-x64
          # Destination path
          path: ClassiCube-x64

      - name: Create the release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          files: |
            ClassiCube-x64/ClassiCube-x64.tar.gz
            ClassiCube-x86/ClassiCube-x86.tar.gz
